project_id = "zzhgbypdlhjjccxsobqp"

[functions.analyze-psych]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.analyze-piq]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.health-check]
verify_jwt = false
